# Actividad 4.1 (Filtrado de datos)
- Miranda Eugenia Colorado Arróniz A01737027

#### Por cada filtro agregar un archivo .csv con el nombre de cada filtro y describir cuales fueron las variables filtradas dentro del script

In [ ]:
# Leer el CSV
import pandas as pd

df = pd.read_csv('Datos_Facturación.csv')

## 1. CVE_CLPV (valores: 1000 a 2000)

In [18]:
cve_clpv = df[(df['CVE_CLPV'] >= 1000) & (df['CVE_CLPV'] <= 2000)]
cve_clpv.to_csv('filtro_CVE_CLPV_1000_2000.csv', index=False)
cve_clpv.head()

,Unnamed: 0,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
18,18,F29432,1965.0,C,2.0,2019-09-05 11:05:04.000,2019-09-05,2019-09-05 00:00:00,2019-09-20,2019-09-06,976.5,0.00,0.0
22,22,F29436,1965.0,C,2.0,2019-09-06 12:01:36.000,2019-09-06,2019-09-06 00:00:00,2019-09-21,2019-09-12,976.5,0.00,0.0
65,65,F29479,1240.0,E,2.0,2019-09-11 18:38:45.000,2019-09-11,2019-09-11 00:00:00,2019-09-11,NaN,4135.0,0.00,0.0
71,71,F29485,1965.0,C,2.0,2019-09-12 12:14:28.000,2019-09-12,2019-09-12 00:00:00,2019-09-27,2019-09-12,976.5,146.48,0.0
72,72,F29486,1965.0,E,2.0,2019-09-12 12:25:52.000,2019-09-12,2019-09-12 00:00:00,2019-09-27,NaN,976.5,146.48,0.0

## 2. CVE_VEND (Todas las claves excepto “5” y “4”)

In [19]:
cve_vend = df[~df['CVE_VEND'].isin([4,5])]
cve_vend.to_csv('filtro_CVE_VEND_excluye_4_5.csv', index=False)
cve_vend.head()

,Unnamed: 0,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
0,0,F29414,2465.0,C,1.0,2019-09-03 08:58:42.000,2019-09-03,2019-09-03 00:00:00,2019-09-18,2019-09-04,3980.00,0.0,0.0
1,1,F29415,3926.0,C,1.0,2019-09-03 09:55:14.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0.0
2,2,F29416,3926.0,C,1.0,2019-09-03 13:25:33.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0.0
3,3,F29417,3926.0,C,1.0,2019-09-03 13:33:23.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-17,1550.00,0.0,0.0
4,4,F29418,6813.0,C,2.0,2019-09-03 14:23:45.000,2019-09-03,2019-09-03 00:00:00,2019-09-03,2019-09-10,2435.44,0.0,0.0

## 3. FECHA_ENT (Fechas de “28/02/2022”)

In [20]:
fecha_ent = df[df['FECHA_ENT'] == '2019-02-28']
fecha_ent.to_csv('filtro_FECHA_ENT_2019-02-28.csv', index=False)
fecha_ent.head()

Empty DataFrame
Columns: [Unnamed: 0, CVE_DOC, CVE_CLPV, STATUS, CVE_VEND, FECHAELAB, FECHA_DOC, FECHA_ENT, FECHA_VEN, FECHA_CANCELA, CAN_TOT, DES_TOT, DES_FIN]
Index: []

## 4. CAN_TOT (Cantidades menores a 5951.7) o STATUS (“E”)

In [21]:
can_tot = df[(df['CAN_TOT'] < 5951.7) | (df['STATUS'] == 'E')]
can_tot.to_csv('filtro_CAN_TOT_menor_5951.7_o_STATUS_E.csv', index=False)
can_tot.head()

,Unnamed: 0,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
0,0,F29414,2465.0,C,1.0,2019-09-03 08:58:42.000,2019-09-03,2019-09-03 00:00:00,2019-09-18,2019-09-04,3980.00,0.0,0.0
1,1,F29415,3926.0,C,1.0,2019-09-03 09:55:14.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0.0
2,2,F29416,3926.0,C,1.0,2019-09-03 13:25:33.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0.0
3,3,F29417,3926.0,C,1.0,2019-09-03 13:33:23.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-17,1550.00,0.0,0.0
4,4,F29418,6813.0,C,2.0,2019-09-03 14:23:45.000,2019-09-03,2019-09-03 00:00:00,2019-09-03,2019-09-10,2435.44,0.0,0.0

## 5. Solo las columnas: CVE_DOC, FECHA_ENT, FECHA_VEN y CAN_TOT

In [22]:
filtro5 = df[['CVE_DOC', 'FECHA_ENT', 'FECHA_VEN', 'CAN_TOT']]
filtro5.to_csv('filtro_columnas_CVE_DOC_FECHA_ENT_FECHA_VEN_CAN_TOT.csv', index=False)
filtro5.head()

  CVE_DOC            FECHA_ENT   FECHA_VEN  CAN_TOT
0  F29414  2019-09-03 00:00:00  2019-09-18  3980.00
1  F29415  2019-09-03 00:00:00  2019-10-03  1550.00
2  F29416  2019-09-03 00:00:00  2019-10-03  1550.00
3  F29417  2019-09-03 00:00:00  2019-10-03  1550.00
4  F29418  2019-09-03 00:00:00  2019-09-03  2435.44

## 6. Solo las filas de 7001-7099

In [23]:
filtro6 = df.iloc[7000:7099]
filtro6.to_csv('filtro_filas_7001_7099.csv', index=False)
filtro6.head()

,Unnamed: 0,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
7000,7000,F36416,3930.0,E,1.0,2021-10-15 08:19:30.557,2021-10-15,2021-10-19 00:00:00,2021-11-14,NaN,28305.00,0.0,0.0
7001,7001,F36417,5271.0,E,3.0,2021-10-15 08:40:29.183,2021-10-15,2021-10-06 00:00:00,2021-11-14,NaN,8555.24,0.0,0.0
7002,7002,F36418,5746.0,E,2.0,2021-10-15 08:51:03.463,2021-10-15,2021-10-14 00:00:00,2021-10-15,NaN,620.77,0.0,0.0
7003,7003,F36419,2163.0,E,3.0,2021-10-15 08:56:23.280,2021-10-15,2021-10-15 00:00:00,2021-10-15,NaN,560.00,0.0,0.0
7004,7004,F36420,1429.0,E,1.0,2021-10-15 09:01:08.393,2021-10-15,2021-10-15 00:00:00,2021-12-14,NaN,23625.00,0.0,0.0

## 7. Index= CVE_VEND (valores: 1, 2) (columna: FECHAELAB)

In [24]:
filtro7 = df[df['CVE_VEND'].isin([1,2])][['FECHAELAB']]
filtro7.to_csv('filtro_CVE_VEND_1_2_FECHAELAB.csv', index=False)
filtro7.head()

                 FECHAELAB
0  2019-09-03 08:58:42.000
1  2019-09-03 09:55:14.000
2  2019-09-03 13:25:33.000
3  2019-09-03 13:33:23.000
4  2019-09-03 14:23:45.000